services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
    volumes:
      - ./backEnd/src/database/sql:/docker-entrypoint-initdb.d
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - $MYSQL_DOCKER_PORT
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
  api:
    build: ./backEnd
    environment:
      - MYSQL_HOST=mysqldb
    ports:
      - "3000:3000"
    depends_on:
      mysqldb:
        condition: service_healthy
  react:
    build: ./frontEnd
    ports:
      - "8000:8000"
    depends_on:
      - api
