services:
  mysqldb:
    image: mysql:8.0
    container_name: ct-mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - $MYSQL_DOCKER_PORT
